### ISSUE TITLE
Full fastboot compatibility

### ISSUE THREAD

**Issue by billdami** [stonecircle/ember-body-class#6]
In fastboot apps, since the body classes are not applied when rendered on the server, any CSS styles dependent on those classes are not applied until after the client-side app boots up and takes over, which results in a undesirable FOUC-like affect, where elements are styled one way on initial page load, then change in style when the ember app loads.

The ember-cli-document-title addon achieves full rendering parity between fastboot/client by checking to see if fastboot's dom renderer is available, and if it is, it uses that, otherwise it falls back to the normal DOM environment implementation. (https://github.com/kimroen/ember-cli-document-title/blob/master/vendor/document-title/document-title.js#L85) 

Would it be possible to do the same thing here?

**Comment by cesarizu** [comment]
It seems that it's not possible without modifying fastboot. See here:

https://github.com/ember-fastboot/fastboot/blob/ff877c738fecc6e4d345c803f77418665a533f00/src/result.js#L37

**Comment by cesarizu** [comment]
I've created a PR at AddJam/ember-body-class#8 that implements fastboot support by adding `script` tags to the body that add the necessary classes. This can certainly be improved in many ways (remove duplicates, add only one tag, etc), but it's a proof-of-concept that it's working.

Currently, the `class` attribute of the body cannot be changed directly, as stated before, because fastboot renders only the children of the body. A more definitive solution would require modifying the [fastboot](https://github.com/ember-fastboot/fastboot/) project.

**Comment by billdami** [comment]
@cesarizu Interesting solution, so for the non-glimmer 2 implementation does that mean that the actual HTML served by fastboot does not have those classes applied to the body, instead those injected script tags just block rendering of the rest of the body on the client side until they have been executed?

That wouldn't be ideal, but at least the silver lining is that Glimmer 2 should hopefully land in ember v2.10, which provides that much cleaner path.

**Comment by cesarizu** [comment]
Yes, it's ugly to add those classes like that, but it works :smile:. The body is rendered just as `<body>`.

I haven't tested this code with glimmer 2 on fastboot yet, just using a normal ember app and the ember-beta and canary branches and it seems to be working. I don't know if fastboot with glimmer 2 renders the whole body tag, but I suspect it doesn't :worried:.

**Comment by mansona** [comment]
@sivakumar-kailasam I have added full Fastboot support to ember-body-class as of version 1.0.0 which was released 9 days ago 🎉 

@billdami sorry for not getting back to you on this issue since we took over the addon, we haven't had a chance to triage the issues yet. Let me know if you have any problems with v1 and we can re-open this issue 👍

**Comment by billdami** [comment]
@mansona thanks for the update! I am testing 1.0.0 in my latest application (running Ember 3.1.1) and noticed an interesting issue. For a route `projects.index` in my app, fastboot renders the following body tag:

```html
 <body  class="null application application projects projects projects index projects projects-index">
```

And in the browser, the body tag renders as:
```html
<body class="null application projects index projects-index ember-application">
```

Not sure if it makes any difference, but I am running with the `@ember/optional-features` package installed, with the following optional features:

```json
{
  "application-template-wrapper": false,
  "template-only-glimmer-components": true
}
```

**Comment by sivakumar-kailasam** [comment]
I noticed null on the guides app too & it's a standard 3.1 app

**Comment by mansona** [comment]
@billdami and @sivakumar-kailasam v1.0.1 has been released that should fix the null issue. I have also fixed the duplication that you were seeing @billdami, not that it would make too much of a difference to the rendering 😂 

Let me know if you have any questions 👍
